name: Bug Report
description: Create a report about a bug inside the library.
body:

  - type: textarea
    id: reproducing-example
    attributes:
      label: Code that causes the issue
      description: Provide a code example that reproduces the problem. Try to keep it short without other dependencies.
      placeholder: |
        ```python
        from telethon.sync import TelegramClient
        ...

        ```
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Explain what you should expect to happen. Include reproduction steps.
      placeholder: |
        "I was doing... I was expecting the following to happen..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: Explain what actually happens.
      placeholder: |
        "This happened instead..."
    validations:
      required: true

  - type: textarea
    id: traceback
    attributes:
      label: Traceback
      description: |
        The traceback, if the problem is a crash.
      placeholder: |
        ```
        Traceback (most recent call last):
          File "code.py", line 1, in <code>

        ```

  - type: input
    id: telethon-version
    attributes:
      label: Telethon version
      description: The output of `python -c "import telethon; print(telethon.__version__)"`.
      placeholder: "1.x"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python version
      description: The output of `python --version`.
      placeholder: "3.x"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system (including distribution name and version)
      placeholder: Windows 11, macOS 13.4, Ubuntu 23.04...
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: |
        Additional details and attachments. Is it a server? Network condition?

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Read this carefully, we will close and ignore your issue if you skimmed through this.
      options:
        - label: The error is in the library's code, and not in my own.
          required: true
        - label: I have searched for this issue before posting it and there isn't an open duplicate.
          required: true
        - label: I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.
          required: true
